version: '3.8'
services:
  backend:
    build: .
    ports:
      - "9000:9000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/Notes
    depends_on:
      - mongo

  mongo:
    image: mongo:7
    restart: always
    ports:
      - "27017:27017"